version: "3.8"

services:
        app:
                build: ./flask/app
                container_name: app
                restart: always
                expose:
                        - 8080
        nginx:
                build: ./nginx
                container_name: nginx
                restart: always
                ports:
                        - "80:80"